consim_core_index:
    pattern: /game
    defaults: { _controller: consim.core.controller.Index:display }

consim_core_travel:
    pattern: /game/travel/{travel_id}
    defaults: { _controller: consim.core.controller.Index:travel, travel_id: 0 }
    requirements:
        travel_id: \w+

consim_core_register:
    pattern: /game/register
    defaults: { _controller: consim.core.controller.Register:display }
