consim_core_index:
    pattern: /consim
    defaults: { _controller: consim.core.controller.Index:display }

consim_core_register:
    pattern: /consim/register
    defaults: { _controller: consim.core.controller.Register:display }
