imports:
    - { resource: tables.yml }

services:
    consim.core.listener:
        class: consim\core\event\listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
        tags:
            - { name: event.listener }

    consim.core.controller.index:
        class: consim\core\controller\Index
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn

    consim.core.controller.action:
        class: consim\core\controller\Action
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn

    consim.core.controller.register:
        class: consim\core\controller\Register
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn

    consim.core.controller.news:
        class: consim\core\controller\News
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn

    consim.core.operators.locations:
        class: consim\core\operators\Locations
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.routes%
            - %tables.consim.locations%
            - %tables.consim.location_types%
            - %tables.consim.provinces%
            - %tables.consim.countries%
            - %tables.consim.buildings%
            - %tables.consim.building_types%
            - %tables.consim.works%

    consim.core.operators.action_lists:
        class: consim\core\operators\ActionLists
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.actions%
            - %tables.consim.travels%

    consim.core.operators.inventory:
        class: consim\core\operators\Inventory
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.inventories%
            - %tables.consim.inventory_items%

    consim.core.entity.building:
        class: consim\core\entity\Building
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.buildings%
            - %tables.consim.building_types%

    consim.core.entity.travel_location:
        class: consim\core\entity\TravelLocation
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.actions%
            - %tables.consim.travels%
            - %tables.consim.locations%
            - %tables.consim.location_types%
            - %tables.consim.provinces%
            - %tables.consim.countries%

    consim.core.entity.travel:
        class: consim\core\entity\Travel
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.actions%
            - %tables.consim.travels%
            - %tables.consim.user%

    consim.core.entity.action:
        class: consim\core\entity\Action
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.actions%

    consim.core.entity.route:
        class: consim\core\entity\Route
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.routes%

    consim.core.entity.province:
        class: consim\core\entity\Province
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.provinces%

    consim.core.entity.route_location:
        class: consim\core\entity\RouteLocation
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.routes%
            - %tables.consim.locations%
            - %tables.consim.location_types%
            - %tables.consim.provinces%
            - %tables.consim.countries%

    consim.core.entity.location:
        class: consim\core\entity\Location
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.locations%
            - %tables.consim.location_types%
            - %tables.consim.provinces%
            - %tables.consim.countries%

    consim.core.entity.location_type:
        class: consim\core\entity\LocationType
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.location_types%

    consim.core.entity.work:
        class: consim\core\entity\Work
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.works%
            
    consim.core.entity.news:
        class: consim\core\entity\News
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.news%
            
    consim.core.entity.news_channel:
        class: consim\core\entity\NewsChannel
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.news_channels%
            
    consim.core.entity.news_topics:
        class: consim\core\entity\NewsTopics
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.news_topics%
            
    consim.core.entity.consim_user:
        class: consim\core\entity\ConsimUser
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.user%
            - %tables.consim.figure%

    consim.core.entity.consim_figure:
        class: consim\core\entity\ConsimFigure
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.figure%

    consim.core.entity.inventory_item:
        class: consim\core\entity\InventoryItem
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.inventory_items%

    consim.core.entity.inventory:
            class: consim\core\entity\Inventory
            scope: prototype # scope MUST be prototype for this to work!
            arguments:
                - @dbal.conn
                - %tables.consim.inventories%
                - %tables.consim.inventory_items%