imports:
    - { resource: tables.yml }

services:
    consim.core.listener:
        class: consim\core\event\listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
        tags:
            - { name: event.listener }
    consim.core.controller.Index:
        class: consim\core\controller\Index
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn
    consim.core.controller.Register:
        class: consim\core\controller\Register
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn
    consim.core.entity.ConsimUser:
        class: consim\core\entity\ConsimUser
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.user%
            - %tables.consim.figure%
    consim.core.entity.ConsimFigure:
        class: consim\core\entity\ConsimFigure
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.figure%
