imports:
    - { resource: tables.yml }
    - { resource: services/controller.yml }
    - { resource: services/entity.yml }
    - { resource: services/operators.yml }

services:
    consim.core.listener:
        class: consim\core\event\listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - @dbal.conn
        tags:
            - { name: event.listener }