imports:
    - { resource: tables.yml }

services:
    consim.core.listener:
        class: consim\core\event\listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
        tags:
            - { name: event.listener }

    consim.core.controller.Index:
        class: consim\core\controller\Index
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn

    consim.core.controller.Action:
        class: consim\core\controller\Action
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn

    consim.core.controller.Register:
        class: consim\core\controller\Register
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn

    consim.core.controller.News:
        class: consim\core\controller\News
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn            

    consim.core.operators.Locations:
        class: consim\core\operators\Locations
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.routes%
            - %tables.consim.locations%
            - %tables.consim.location_types%
            - %tables.consim.provinces%
            - %tables.consim.countries%
            - %tables.consim.buildings%
            - %tables.consim.building_types%

    consim.core.operators.ActionLists:
        class: consim\core\operators\ActionLists
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.actions%
            - %tables.consim.travels%

    consim.core.entity.Building:
        class: consim\core\entity\Building
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.buildings%
            - %tables.consim.building_types%

    consim.core.entity.TravelLocation:
        class: consim\core\entity\TravelLocation
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.actions%
            - %tables.consim.travels%
            - %tables.consim.locations%
            - %tables.consim.location_types%
            - %tables.consim.provinces%
            - %tables.consim.countries%

    consim.core.entity.Travel:
        class: consim\core\entity\Travel
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.actions%
            - %tables.consim.travels%
            - %tables.consim.user%

    consim.core.entity.Action:
        class: consim\core\entity\Action
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.actions%

    consim.core.entity.Route:
        class: consim\core\entity\Route
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.routes%

    consim.core.entity.Province:
        class: consim\core\entity\Province
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.provinces%

    consim.core.entity.RouteLocation:
        class: consim\core\entity\RouteLocation
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.routes%
            - %tables.consim.locations%
            - %tables.consim.location_types%
            - %tables.consim.provinces%
            - %tables.consim.countries%

    consim.core.entity.Location:
        class: consim\core\entity\Location
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.locations%
            - %tables.consim.location_types%
            - %tables.consim.provinces%
            - %tables.consim.countries%

    consim.core.entity.LocationType:
        class: consim\core\entity\LocationType
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.location_types%
            
    consim.core.entity.News:
        class: consim\core\entity\News
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.news%
            
    consim.core.entity.NewsChannel:
        class: consim\core\entity\NewsChannel
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.news_channels%
            
    consim.core.entity.NewsTopics:
        class: consim\core\entity\NewsTopics
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.news_topics%
            
    consim.core.entity.ConsimUser:
        class: consim\core\entity\ConsimUser
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.user%
            - %tables.consim.figure%

    consim.core.entity.ConsimFigure:
        class: consim\core\entity\ConsimFigure
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.consim.figure%
