parameters:
    tables.consim.user: %core.table_prefix%consim_user
    tables.consim.figure: %core.table_prefix%consim_figure
    tables.consim.locations: %core.table_prefix%consim_locations
    tables.consim.location_types: %core.table_prefix%consim_location_types
    tables.consim.provinces: %core.table_prefix%consim_provinces
