parameters:
    tables.consim.user: %core.table_prefix%consim_user
    tables.consim.figure: %core.table_prefix%consim_figure
    tables.consim.skills: %core.table_prefix%consim_skills
    tables.consim.user_skills: %core.table_prefix%consim_user_skills
    tables.consim.items: %core.table_prefix%consim_items
    tables.consim.inventory_items: %core.table_prefix%consim_inventory_items
    tables.consim.locations: %core.table_prefix%consim_locations
    tables.consim.location_types: %core.table_prefix%consim_location_types
    tables.consim.provinces: %core.table_prefix%consim_provinces
    tables.consim.countries: %core.table_prefix%consim_countries
    tables.consim.routes: %core.table_prefix%consim_routes
    tables.consim.actions: %core.table_prefix%consim_actions
    tables.consim.buildings: %core.table_prefix%consim_buildings
    tables.consim.building_types: %core.table_prefix%consim_building_types
    tables.consim.works: %core.table_prefix%consim_works
    tables.consim.work_outputs: %core.table_prefix%consim_work_outputs
    tables.consim.news: %core.table_prefix%consim_news
    tables.consim.news_channels: %core.table_prefix%consim_news_channel
    tables.consim.news_topics: %core.table_prefix%consim_news_topics
    tables.consim.anniversary: %core.table_prefix%consim_anniversary
