parameters:
    tables.consim.user: %core.table_prefix%consim_user
    tables.consim.figure: %core.table_prefix%consim_figure
    tables.consim.locations: %core.table_prefix%consim_locations
    tables.consim.location_types: %core.table_prefix%consim_location_types
    tables.consim.provinces: %core.table_prefix%consim_provinces
    tables.consim.countries: %core.table_prefix%consim_countries
    tables.consim.routes: %core.table_prefix%consim_routes
    tables.consim.actions: %core.table_prefix%consim_actions
    tables.consim.travels: %core.table_prefix%consim_travels
    tables.consim.buildings: %core.table_prefix%consim_buildings
<<<<<<< HEAD
    tables.consim.building_types: %core.table_prefix%consim_building_types
=======
    tables.consim.location_buildings: %core.table_prefix%consim_location_buildings
    tables.consim.news: %core.table_prefix%consim_news
    tables.consim.news_channels: %core.table_prefix%consim_news_channel
    tables.consim.news_topics: %core.table_prefix%consim_news_topics
>>>>>>> refs/remotes/origin/master
