imports:
    - { resource: tables.yml }

services:
    consim.core.controller.location:
            class: consim\core\controller\LocationController
            arguments:
                - @config
                - @service_container
                - @controller.helper
                - @user
                - @template
                - @request
                - @dbal.conn
                - @consim.core.service.action
                - @consim.core.service.building
                - @consim.core.service.inventory
                - @consim.core.service.location
                - @consim.core.service.map
                - @consim.core.service.user
                - @consim.core.service.user_skill
                - @consim.core.service.weather
                - @consim.core.service.widget
                - @consim.core.service.work

    consim.core.controller.action:
        class: consim\core\controller\ActionController
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @consim.core.service.action
            - @consim.core.service.building
            - @consim.core.service.inventory
            - @consim.core.service.location
            - @consim.core.service.route
            - @consim.core.service.user
            - @consim.core.service.user_skill
            - @consim.core.service.weather
            - @consim.core.service.widget
            - @consim.core.service.work

    consim.core.controller.request:
        class: consim\core\controller\RequestController
        arguments:
            - @service_container
            - @controller.helper
            - @user
            - @request

    consim.core.controller.register:
        class: consim\core\controller\RegisterController
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @user
            - @template
            - @request
            - @dbal.conn
