imports:
    - { resource: tables.yml }

services:
  consim.core.service.location:
        class: consim\core\service\LocationService
        arguments:
            - @dbal.conn
            - @service_container
            - %tables.consim.routes%
            - %tables.consim.locations%
            - %tables.consim.location_types%
            - %tables.consim.provinces%
            - %tables.consim.countries%
            - %tables.consim.buildings%
            - %tables.consim.building_types%
            - %tables.consim.works%
            - %tables.consim.skills%
            - %tables.consim.items%

  consim.core.service.action:
      class: consim\core\service\ActionService
      arguments:
          - @dbal.conn
          - @service_container
          - %tables.consim.actions%

  consim.core.service.inventory:
      class: consim\core\service\InventoryService
      arguments:
          - @dbal.conn
          - @service_container
          - %tables.consim.items%
          - %tables.consim.inventory_items%

  consim.core.service.user_skill:
      class: consim\core\service\UserSkillService
      arguments:
          - @dbal.conn
          - @service_container
          - %tables.consim.skills%
          - %tables.consim.user_skills%

  consim.core.service.work:
      class: consim\core\service\WorkService
      arguments:
          - @dbal.conn
          - @service_container
          - %tables.consim.works%
          - %tables.consim.work_outputs%
          - %tables.consim.skills%
          - %tables.consim.items%